/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package homesportboost;

import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author 
 */
public class Accueil2Frame extends javax.swing.JFrame {

    public static String utilisateur;
    public static String[][] tableauDefis;
    public static String[][] tableauClass;  // onglet-2
    public static String idDefis;
    private int pts;
    private int dtt;
    private String  bestDefi;
    
    DefaultTableModel model;
    DefaultTableModel model2;  //Onglet 2
    /**
     * Creates new form Accueil2Frame
     */
    
    public Accueil2Frame(String user) {
        initComponents();
        menuStat.setVisible(true);
        menuCons.setVisible(false);
        
        recupTriMaj();
        utilisateur = user;
        // affichage du nom de l'utilisateur après sa connexion
        LabelUtilisateur.setText(utilisateur);

        // onglet-1 remplissage du tableau de défis
        try {
            File file = new File("src/homesportboost/defis.csv");
            String filename = file.getAbsolutePath();
            tableauDefis = Controller.readDefis(filename);
            model = (DefaultTableModel) table.getModel();

            for (int boucle = 0; boucle < tableauDefis.length; boucle++) {
                String numero = tableauDefis[boucle][0];
                String defis = tableauDefis[boucle][1];
                String points = tableauDefis[boucle][2];
                String realise = tableauDefis[boucle][3];
                model.insertRow(model.getRowCount(), new Object[]{numero, defis, points, realise});
            }
            
            //Affichage du défi du jour aléatoirement pris dans le tableau des défis
            int tailleTableau = tableauDefis.length;
            Random random = new Random();
            int defiDuJour = random.nextInt(tailleTableau);
            Objectif.setText(tableauDefis[defiDuJour][1]);
            NbPtsImport.setText(tableauDefis[defiDuJour][2]);
            
        } catch (IOException ex) {
            Logger.getLogger(HomeSportBoost.class.getName()).log(Level.SEVERE, null, ex);
        }
        setStat();
        setPro(pts);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Accueil = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        BonjourTexte = new javax.swing.JLabel();
        LabelUtilisateur = new javax.swing.JLabel();
        VoiciObjectifToday = new javax.swing.JLabel();
        VoiciObjectifToday2 = new javax.swing.JLabel();
        Objectif = new javax.swing.JLabel();
        IlVousApportera = new javax.swing.JLabel();
        NbPtsImport = new javax.swing.JLabel();
        Xpoints = new javax.swing.JLabel();
        PourConfirmerVotreAvance = new javax.swing.JLabel();
        votreRetardChoisissez = new javax.swing.JLabel();
        ValidezVotreDefi = new javax.swing.JLabel();
        idText = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Image = new javax.swing.JLabel();
        Classement = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        actualise_tables = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();
        ImagesOnglet2 = new javax.swing.JLabel();
        monComptePanel = new javax.swing.JPanel();
        menuCons = new javax.swing.JPanel();
        choixConseil = new javax.swing.JComboBox<>();
        boutonCons = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        texteConseil = new javax.swing.JTextArea();
        menuStat = new javax.swing.JPanel();
        parcoursLVL1 = new javax.swing.JLabel();
        textProgression = new javax.swing.JLabel();
        nextLVL = new javax.swing.JLabel();
        statsStats = new javax.swing.JLabel();
        pointsTotaux = new javax.swing.JLabel();
        meilleurDefi = new javax.swing.JLabel();
        showPointsTotaux = new javax.swing.JLabel();
        defisToto = new javax.swing.JLabel();
        showNbDefis = new javax.swing.JLabel();
        showBestDefi = new javax.swing.JLabel();
        yourLVL = new javax.swing.JLabel();
        barreProPro = new javax.swing.JProgressBar();
        Manu = new javax.swing.JPanel();
        panelStats = new javax.swing.JPanel();
        textStats = new javax.swing.JLabel();
        panelConseil = new javax.swing.JPanel();
        textConseil1 = new javax.swing.JLabel();
        seDeco = new javax.swing.JPanel();
        textSeDeco = new javax.swing.JLabel();
        baquegrounde = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        Accueil.setLayout(null);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numéro", "Défis", "Points", "Réalisé ?"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setMinWidth(60);
            table.getColumnModel().getColumn(0).setPreferredWidth(60);
            table.getColumnModel().getColumn(0).setMaxWidth(60);
            table.getColumnModel().getColumn(1).setMinWidth(470);
            table.getColumnModel().getColumn(1).setPreferredWidth(470);
            table.getColumnModel().getColumn(1).setMaxWidth(470);
            table.getColumnModel().getColumn(2).setMinWidth(60);
            table.getColumnModel().getColumn(2).setPreferredWidth(60);
            table.getColumnModel().getColumn(2).setMaxWidth(60);
            table.getColumnModel().getColumn(3).setMinWidth(70);
            table.getColumnModel().getColumn(3).setPreferredWidth(70);
            table.getColumnModel().getColumn(3).setMaxWidth(70);
        }

        Accueil.add(jScrollPane1);
        jScrollPane1.setBounds(590, 170, 670, 370);

        BonjourTexte.setFont(new java.awt.Font("Ebrima", 0, 24)); // NOI18N
        BonjourTexte.setForeground(new java.awt.Color(255, 255, 255));
        BonjourTexte.setText("Bonjour");
        Accueil.add(BonjourTexte);
        BonjourTexte.setBounds(10, 0, 100, 29);

        LabelUtilisateur.setFont(new java.awt.Font("Ebrima", 0, 24)); // NOI18N
        LabelUtilisateur.setForeground(new java.awt.Color(255, 255, 255));
        LabelUtilisateur.setText("toto");
        Accueil.add(LabelUtilisateur);
        LabelUtilisateur.setBounds(100, 0, 180, 29);

        VoiciObjectifToday.setFont(new java.awt.Font("Ebrima", 0, 48)); // NOI18N
        VoiciObjectifToday.setForeground(new java.awt.Color(255, 255, 255));
        VoiciObjectifToday.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        VoiciObjectifToday.setText("Voici votre défi");
        Accueil.add(VoiciObjectifToday);
        VoiciObjectifToday.setBounds(80, 180, 410, 57);

        VoiciObjectifToday2.setFont(new java.awt.Font("Ebrima", 0, 48)); // NOI18N
        VoiciObjectifToday2.setForeground(new java.awt.Color(255, 255, 255));
        VoiciObjectifToday2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        VoiciObjectifToday2.setText("du jour :");
        Accueil.add(VoiciObjectifToday2);
        VoiciObjectifToday2.setBounds(80, 230, 410, 57);

        Objectif.setFont(new java.awt.Font("Ebrima", 0, 24)); // NOI18N
        Objectif.setForeground(new java.awt.Color(255, 255, 255));
        Objectif.setText("...");
        Accueil.add(Objectif);
        Objectif.setBounds(110, 310, 360, 70);

        IlVousApportera.setFont(new java.awt.Font("Ebrima", 0, 48)); // NOI18N
        IlVousApportera.setForeground(new java.awt.Color(255, 255, 255));
        IlVousApportera.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IlVousApportera.setText("Il vous rapportera");
        Accueil.add(IlVousApportera);
        IlVousApportera.setBounds(80, 390, 410, 57);

        NbPtsImport.setFont(new java.awt.Font("Ebrima", 0, 48)); // NOI18N
        NbPtsImport.setForeground(new java.awt.Color(255, 255, 255));
        NbPtsImport.setText("...");
        Accueil.add(NbPtsImport);
        NbPtsImport.setBounds(160, 500, 80, 57);

        Xpoints.setFont(new java.awt.Font("Ebrima", 0, 48)); // NOI18N
        Xpoints.setForeground(new java.awt.Color(255, 255, 255));
        Xpoints.setText("points");
        Accueil.add(Xpoints);
        Xpoints.setBounds(280, 500, 170, 57);

        PourConfirmerVotreAvance.setFont(new java.awt.Font("Ebrima", 0, 30)); // NOI18N
        PourConfirmerVotreAvance.setForeground(new java.awt.Color(255, 255, 255));
        PourConfirmerVotreAvance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PourConfirmerVotreAvance.setText("Pour confirmer votre avance ou rattraper");
        Accueil.add(PourConfirmerVotreAvance);
        PourConfirmerVotreAvance.setBounds(630, 30, 600, 36);

        votreRetardChoisissez.setFont(new java.awt.Font("Ebrima", 0, 30)); // NOI18N
        votreRetardChoisissez.setForeground(new java.awt.Color(255, 255, 255));
        votreRetardChoisissez.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        votreRetardChoisissez.setText("votre retard, choisissez un défi, réalisez-le");
        Accueil.add(votreRetardChoisissez);
        votreRetardChoisissez.setBounds(620, 80, 630, 36);

        ValidezVotreDefi.setFont(new java.awt.Font("Ebrima", 0, 30)); // NOI18N
        ValidezVotreDefi.setForeground(new java.awt.Color(255, 255, 255));
        ValidezVotreDefi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ValidezVotreDefi.setText("Valider votre défi en entrant son numéro");
        Accueil.add(ValidezVotreDefi);
        ValidezVotreDefi.setBounds(620, 570, 640, 36);

        idText.setFont(new java.awt.Font("Ebrima", 0, 24)); // NOI18N
        idText.setForeground(new java.awt.Color(255, 255, 255));
        idText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        idText.setText("N°");
        idText.setBorder(null);
        idText.setOpaque(false);
        idText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                idTextMouseClicked(evt);
            }
        });
        Accueil.add(idText);
        idText.setBounds(840, 640, 40, 30);

        jButton1.setText("Valider");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Accueil.add(jButton1);
        jButton1.setBounds(970, 630, 90, 40);

        Image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homesportboost/fondOnglet2Vierge.png"))); // NOI18N
        Accueil.add(Image);
        Image.setBounds(0, 0, 1370, 720);

        jTabbedPane1.addTab("Accueil", Accueil);

        Classement.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Ebrima", 0, 22)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("name2");
        Classement.add(jLabel13);
        jLabel13.setBounds(450, 90, 130, 27);

        jLabel8.setFont(new java.awt.Font("Ebrima", 0, 22)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("pos2");
        Classement.add(jLabel8);
        jLabel8.setBounds(470, 150, 70, 27);

        jLabel12.setFont(new java.awt.Font("Ebrima", 0, 22)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("name1");
        Classement.add(jLabel12);
        jLabel12.setBounds(600, 170, 130, 27);

        jLabel5.setFont(new java.awt.Font("Ebrima", 0, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("pos1");
        Classement.add(jLabel5);
        jLabel5.setBounds(630, 230, 60, 27);

        jLabel14.setFont(new java.awt.Font("Ebrima", 0, 22)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("name3");
        Classement.add(jLabel14);
        jLabel14.setBounds(740, 90, 150, 27);

        jLabel9.setFont(new java.awt.Font("Ebrima", 0, 22)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("pos3");
        Classement.add(jLabel9);
        jLabel9.setBounds(780, 160, 60, 27);

        actualise_tables.setText("Actualiser le classement");
        actualise_tables.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualise_tablesActionPerformed(evt);
            }
        });
        Classement.add(actualise_tables);
        actualise_tables.setBounds(570, 400, 190, 40);

        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Position", "Nom", "Points"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(table2);

        Classement.add(jScrollPane2);
        jScrollPane2.setBounds(390, 460, 550, 240);

        ImagesOnglet2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homesportboost/FondOnglet2.png"))); // NOI18N
        Classement.add(ImagesOnglet2);
        ImagesOnglet2.setBounds(0, 0, 1280, 720);

        jTabbedPane1.addTab("Classement", Classement);

        monComptePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuCons.setBackground(new java.awt.Color(153, 255, 255));
        menuCons.setOpaque(false);

        choixConseil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Motivation", "Efficacité" }));

        boutonCons.setText("Ok!");
        boutonCons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonConsActionPerformed(evt);
            }
        });

        texteConseil.setColumns(20);
        texteConseil.setRows(5);
        jScrollPane3.setViewportView(texteConseil);

        javax.swing.GroupLayout menuConsLayout = new javax.swing.GroupLayout(menuCons);
        menuCons.setLayout(menuConsLayout);
        menuConsLayout.setHorizontalGroup(
            menuConsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuConsLayout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(choixConseil, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(boutonCons, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(215, Short.MAX_VALUE))
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        menuConsLayout.setVerticalGroup(
            menuConsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuConsLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(menuConsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(choixConseil, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boutonCons, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE))
        );

        monComptePanel.add(menuCons, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 970, 710));

        menuStat.setOpaque(false);

        parcoursLVL1.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        parcoursLVL1.setForeground(new java.awt.Color(255, 255, 255));
        parcoursLVL1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/star_half_empty_30px.png"))); // NOI18N
        parcoursLVL1.setText("Ton Titre");

        textProgression.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        textProgression.setForeground(new java.awt.Color(255, 255, 255));
        textProgression.setText("Progression :");

        nextLVL.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nextLVL.setForeground(new java.awt.Color(255, 255, 255));
        nextLVL.setText("next");

        statsStats.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        statsStats.setForeground(new java.awt.Color(255, 255, 255));
        statsStats.setText("Réussites :");
        statsStats.setMinimumSize(new java.awt.Dimension(151, 32));
        statsStats.setPreferredSize(new java.awt.Dimension(151, 32));

        pointsTotaux.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        pointsTotaux.setForeground(new java.awt.Color(255, 255, 255));
        pointsTotaux.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pointsTotaux.setText("Points Totaux");
        pointsTotaux.setMinimumSize(new java.awt.Dimension(69, 20));

        meilleurDefi.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        meilleurDefi.setForeground(new java.awt.Color(255, 255, 255));
        meilleurDefi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        meilleurDefi.setText("Meilleur Défi Réalisé");

        showPointsTotaux.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        showPointsTotaux.setForeground(new java.awt.Color(255, 255, 255));
        showPointsTotaux.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        showPointsTotaux.setText("Points");

        defisToto.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        defisToto.setForeground(new java.awt.Color(255, 255, 255));
        defisToto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        defisToto.setText("Défis Totaux");
        defisToto.setMinimumSize(new java.awt.Dimension(69, 20));

        showNbDefis.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        showNbDefis.setForeground(new java.awt.Color(255, 255, 255));
        showNbDefis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        showNbDefis.setText("Défis");

        showBestDefi.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        showBestDefi.setForeground(new java.awt.Color(255, 255, 255));
        showBestDefi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        showBestDefi.setText("Best");

        yourLVL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        yourLVL.setForeground(new java.awt.Color(255, 255, 255));
        yourLVL.setText("titre");

        barreProPro.setForeground(new java.awt.Color(0, 0, 0));
        barreProPro.setMaximum(70);

        javax.swing.GroupLayout menuStatLayout = new javax.swing.GroupLayout(menuStat);
        menuStat.setLayout(menuStatLayout);
        menuStatLayout.setHorizontalGroup(
            menuStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuStatLayout.createSequentialGroup()
                .addGroup(menuStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuStatLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(showPointsTotaux, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105)
                        .addComponent(showNbDefis, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(menuStatLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(textProgression)
                        .addGap(104, 104, 104)
                        .addComponent(parcoursLVL1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(yourLVL, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(menuStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuStatLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(barreProPro, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuStatLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(menuStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nextLVL, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(showBestDefi, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuStatLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(statsStats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(pointsTotaux, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(defisToto, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(meilleurDefi, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        menuStatLayout.setVerticalGroup(
            menuStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuStatLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addGroup(menuStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textProgression, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(parcoursLVL1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(yourLVL, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(barreProPro, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(nextLVL, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                .addGroup(menuStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuStatLayout.createSequentialGroup()
                        .addGroup(menuStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(statsStats, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pointsTotaux, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(defisToto, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(meilleurDefi))
                        .addGap(193, 193, 193))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuStatLayout.createSequentialGroup()
                        .addGroup(menuStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(showPointsTotaux, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(showNbDefis, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(showBestDefi, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(74, 74, 74))))
        );

        monComptePanel.add(menuStat, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 970, 710));

        Manu.setBackground(new java.awt.Color(76, 134, 136));

        panelStats.setBackground(new java.awt.Color(65, 159, 158));
        panelStats.setPreferredSize(new java.awt.Dimension(191, 69));
        panelStats.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelStatsMousePressed(evt);
            }
        });

        textStats.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textStats.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/combo_chart_24px.png"))); // NOI18N
        textStats.setText("Stats");

        javax.swing.GroupLayout panelStatsLayout = new javax.swing.GroupLayout(panelStats);
        panelStats.setLayout(panelStatsLayout);
        panelStatsLayout.setHorizontalGroup(
            panelStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStatsLayout.createSequentialGroup()
                .addComponent(textStats, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 119, Short.MAX_VALUE))
        );
        panelStatsLayout.setVerticalGroup(
            panelStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelStatsLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(textStats, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        panelConseil.setBackground(new java.awt.Color(109, 158, 149));
        panelConseil.setPreferredSize(new java.awt.Dimension(191, 69));
        panelConseil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelConseilMousePressed(evt);
            }
        });

        textConseil1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textConseil1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/about_30px.png"))); // NOI18N
        textConseil1.setText("Conseil");

        javax.swing.GroupLayout panelConseilLayout = new javax.swing.GroupLayout(panelConseil);
        panelConseil.setLayout(panelConseilLayout);
        panelConseilLayout.setHorizontalGroup(
            panelConseilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConseilLayout.createSequentialGroup()
                .addComponent(textConseil1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelConseilLayout.setVerticalGroup(
            panelConseilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConseilLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(textConseil1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        seDeco.setBackground(new java.awt.Color(109, 158, 149));
        seDeco.setPreferredSize(new java.awt.Dimension(191, 69));
        seDeco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                seDecoMousePressed(evt);
            }
        });

        textSeDeco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textSeDeco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout_rounded_left_32px.png"))); // NOI18N
        textSeDeco.setText("Se déconnecter");

        javax.swing.GroupLayout seDecoLayout = new javax.swing.GroupLayout(seDeco);
        seDeco.setLayout(seDecoLayout);
        seDecoLayout.setHorizontalGroup(
            seDecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seDecoLayout.createSequentialGroup()
                .addComponent(textSeDeco, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        seDecoLayout.setVerticalGroup(
            seDecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seDecoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textSeDeco, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ManuLayout = new javax.swing.GroupLayout(Manu);
        Manu.setLayout(ManuLayout);
        ManuLayout.setHorizontalGroup(
            ManuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelStats, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
            .addComponent(panelConseil, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
            .addComponent(seDeco, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
        );
        ManuLayout.setVerticalGroup(
            ManuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManuLayout.createSequentialGroup()
                .addContainerGap(231, Short.MAX_VALUE)
                .addComponent(panelStats, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelConseil, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(213, 213, 213)
                .addComponent(seDeco, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        monComptePanel.add(Manu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 720));

        baquegrounde.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homesportboost/fondOnglet3.png"))); // NOI18N
        monComptePanel.add(baquegrounde, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        jLabel1.setText("jLabel1");
        monComptePanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, -1, -1));

        jTabbedPane1.addTab("Mon Compte", monComptePanel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void onClick(JPanel pane){
        pane.setBackground(new Color(65,159,158));
    }
    
    private void onLeaveClick(JPanel pane){
        pane.setBackground(new Color(109,158,149));
    }
    
    private void setStat(){
          
        
            pts=0;
            dtt=0;
            bestDefi="";
            int max=0;
            int number;
            for (int boucle = 0; boucle < tableauDefis.length; boucle++) {

                String numero = tableauDefis[boucle][0];
                String defis = tableauDefis[boucle][1];
                String points = tableauDefis[boucle][2];
                number = Integer.parseInt(points);
                
                String realise = tableauDefis[boucle][3];

                if("oui".equals(realise)){
                    dtt++;
                    pts=pts+number;
                }
                if(number>max){
                    max=number;
                    bestDefi=defis;
                }
            }
            showBestDefi.setText(bestDefi);
            showPointsTotaux.setText(String.valueOf(pts));
            showNbDefis.setText(String.valueOf(dtt));

        
    }
    
    private void setPro(int pts){
        barreProPro.setValue(pts);
        int next=0;
        if(pts<10){
            yourLVL.setText("T'es éclaté");
            next=10-pts;
            nextLVL.setText("Il te reste "+next+" point(s) avant le palier suivant");
            yourLVL.setForeground(new java.awt.Color(40, 194, 27));
        }else if(pts >= 10 && pts <20){
            yourLVL.setText("Bronze");
            next=20-pts;
            nextLVL.setText("Il te reste "+next+" point(s) avant le palier suivant");
            yourLVL.setForeground(new java.awt.Color(223, 147, 13));
        }else if(pts >= 20 && pts < 30){
            yourLVL.setText("Argent");
            next=30-pts;
            nextLVL.setText("Il te reste "+next+" point(s) avant le palier suivant");
            yourLVL.setForeground(new java.awt.Color(209, 204, 196));
        } else if (pts >= 30 && pts <40){
            yourLVL.setText("Or");
            next=40-pts;
            nextLVL.setText("Il te reste "+next+" point(s) avant le palier suivant");
            yourLVL.setForeground(new java.awt.Color(251, 231, 28));
        } else if(pts >= 40 && pts <50){
            yourLVL.setText("Platine");
            next=50-pts;
            nextLVL.setText("Il te reste "+next+" point(s) avant le palier suivant");
            yourLVL.setForeground(new java.awt.Color(143, 141, 254));
        } else if(pts >= 50 && pts <60){
            yourLVL.setText("Diamant");
            next=60-pts;
            nextLVL.setText("Il te reste "+next+"point(s)  avant le palier suivant");
            yourLVL.setForeground(new java.awt.Color(48, 149, 239));
        } else if(pts >= 60){
            yourLVL.setText("Cristal");
            nextLVL.setText("BOGOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOS");
            yourLVL.setForeground(new java.awt.Color(229, 48, 239));
        }
    }

    
    private void idTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idTextMouseClicked
        // quand on clique dans la case pour entrer l'id du défis qu'on veut valider
        idText.setText("");
    }//GEN-LAST:event_idTextMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // quand on clique pour valider un défis
        idDefis = idText.getText();
        try {
            // on appele le controlleur qui change non par oui
            Controller.valideDefis(idDefis);
            updateTable(); //-------------------------------------------TODO
            setStat();
            setPro(pts);
        } catch (IOException ex) {
            Logger.getLogger(Accueil2Frame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void actualise_tablesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualise_tablesActionPerformed
        try {
            // méthode pourtextProgressioniser le classement (le podium, et le tableau à partir de la 4eme position)
            // on appuie sur le bouton pour actualiser
            // on récupère le nouveau tableau
            // on ajoute les points dans le fichier de classement
            Controller.ajoutePoints(idDefis);
            recupTriMaj();
        } catch (IOException ex) {
            Logger.getLogger(Accueil2Frame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_actualise_tablesActionPerformed

    private void boutonConsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonConsActionPerformed
        // TODO add your handling code here:
        try{
        File file = new File("src/homesportboost/conseil.csv");
        String filename = file.getAbsolutePath();
        if ("Motivation".equals(choixConseil.getSelectedItem().toString())){
            String nb="1";
            String resu = Controller.readConseil(filename, nb);
            texteConseil.setText(resu);
        }else if ("Efficacité".equals(choixConseil.getSelectedItem().toString())) {
            String nb="2";
            String resu = Controller.readConseil(filename, nb);
            texteConseil.setText(resu);
        }
        
        } catch (IOException ex) {
            Logger.getLogger(HomeSportBoost.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_boutonConsActionPerformed

    private void panelStatsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelStatsMousePressed
        // TODO add your handling code here:
        onClick(panelStats);
        onLeaveClick(panelConseil);
        menuCons.setVisible(false);
        if(menuStat.isVisible()==false){
            menuStat.setVisible(true);
        }
    }//GEN-LAST:event_panelStatsMousePressed

    private void panelConseilMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelConseilMousePressed
        // TODO add your handling code here:
        onLeaveClick(panelStats);
        onClick(panelConseil);
        menuStat.setVisible(false);
        menuCons.setVisible(true);
    }//GEN-LAST:event_panelConseilMousePressed

    private void seDecoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seDecoMousePressed
        dispose();
    }//GEN-LAST:event_seDecoMousePressed

    private void updateTable() {      
        
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        try {
            while (model.getRowCount() > 0) {
                model.setRowCount(0);
            }
            // remplissage du tableau de défis
            File file = new File("src/homesportboost/defis.csv");
            String filename = file.getAbsolutePath();
            tableauDefis = Controller.readDefis(filename);
            model = (DefaultTableModel) table.getModel();

            for (int boucle = 0; boucle < tableauDefis.length; boucle++) {
                String numero = tableauDefis[boucle][0];
                String defis = tableauDefis[boucle][1];
                String points = tableauDefis[boucle][2];
                String realise = tableauDefis[boucle][3];
                model.insertRow(model.getRowCount(), new Object[]{numero, defis, points, realise});
            }
        } catch (IOException e) {
            System.out.println(e);
        }
        
    }
    
    
    
    
    private void recupTriMaj() {
        // on récupère le nouveau tableau
        File file = new File("src/homesportboost/classement.csv");
        String filename = file.getAbsolutePath();
        try {
            tableauClass = Controller.readClassement(filename);
        } catch (IOException ex) {
            Logger.getLogger(Accueil2Frame.class.getName()).log(Level.SEVERE, null, ex);
        }

        // ça trie et retourne un tableau trié
        String[][] newArray;
        newArray = Controller.sortAndDisplay2DArrays(tableauClass);

        // on met à jour le tableau (graphique, jTable)
        updateTable2(newArray);     // met à jour le tableau du classement (sans les 3 premiers
        afficheles3premiers(newArray);    // récupère et affiche les 3 premiers du classement
    }
    
    // methode permettant d actualiser le tableau
    private void updateTable2(String[][] myArray) {
        DefaultTableModel model = (DefaultTableModel) table2.getModel();
        // on remet à 0 le nombre de lignes sans pour autant les supprimer
        while (model.getRowCount() > 0) {
            model.setRowCount(0);
        }
        // re remplissage tableau classement onglet-2
        model = (DefaultTableModel) table2.getModel();

        // on remplit le tableau à partir de la 4eme position
        for (int i = 3; i < myArray.length; i++) {
            String position = Integer.toString(i + 1);
            String username = myArray[i][0];
            String points = myArray[i][1];
            model.insertRow(model.getRowCount(), new Object[]{position, username, points});
        }
    }

    // onglet-2 méthode permettant d'afficher les 3 premiers du classement dans des jLablel différents
    private void afficheles3premiers(String[][] newArray) {
        try {
            // on récupère les noms et les points du podium
            String name1 = newArray[0][0];
            String name2 = newArray[1][0];
            String name3 = newArray[2][0];

            String pos1 = newArray[0][1];
            String pos2 = newArray[1][1];
            String pos3 = newArray[2][1];

            // affichage des noms en 12, 13 14
            jLabel12.setText(name1);
            jLabel13.setText(name2);
            jLabel14.setText(name3);
            // affichage des points en 5, 8 et 9
            jLabel5.setText(pos1);
            jLabel8.setText(pos2);
            jLabel9.setText(pos3);
        } catch (Exception e) {
            System.out.println("error afficheles3premiers() : " + e);
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Accueil2Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Accueil2Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Accueil2Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Accueil2Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Accueil2Frame(utilisateur).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Accueil;
    private javax.swing.JLabel BonjourTexte;
    private javax.swing.JPanel Classement;
    private javax.swing.JLabel IlVousApportera;
    private javax.swing.JLabel Image;
    private javax.swing.JLabel ImagesOnglet2;
    private javax.swing.JLabel LabelUtilisateur;
    private javax.swing.JPanel Manu;
    private javax.swing.JLabel NbPtsImport;
    private javax.swing.JLabel Objectif;
    private javax.swing.JLabel PourConfirmerVotreAvance;
    private javax.swing.JLabel ValidezVotreDefi;
    private javax.swing.JLabel VoiciObjectifToday;
    private javax.swing.JLabel VoiciObjectifToday2;
    private javax.swing.JLabel Xpoints;
    private javax.swing.JButton actualise_tables;
    private javax.swing.JLabel baquegrounde;
    private javax.swing.JProgressBar barreProPro;
    private javax.swing.JButton boutonCons;
    private javax.swing.JComboBox<String> choixConseil;
    private javax.swing.JLabel defisToto;
    private javax.swing.JTextField idText;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel meilleurDefi;
    private javax.swing.JPanel menuCons;
    private javax.swing.JPanel menuStat;
    private javax.swing.JPanel monComptePanel;
    private javax.swing.JLabel nextLVL;
    private javax.swing.JPanel panelConseil;
    private javax.swing.JPanel panelStats;
    private javax.swing.JLabel parcoursLVL1;
    private javax.swing.JLabel pointsTotaux;
    private javax.swing.JPanel seDeco;
    private javax.swing.JLabel showBestDefi;
    private javax.swing.JLabel showNbDefis;
    private javax.swing.JLabel showPointsTotaux;
    private javax.swing.JLabel statsStats;
    private javax.swing.JTable table;
    private javax.swing.JTable table2;
    private javax.swing.JLabel textConseil1;
    private javax.swing.JLabel textProgression;
    private javax.swing.JLabel textSeDeco;
    private javax.swing.JLabel textStats;
    private javax.swing.JTextArea texteConseil;
    private javax.swing.JLabel votreRetardChoisissez;
    private javax.swing.JLabel yourLVL;
    // End of variables declaration//GEN-END:variables
}
